version: "3.8"

services:
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=production
    # Removing volume mounts that might be causing permission issues
    restart: unless-stopped

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/healthcare
      - PORT=8000
      - JWT_SECRET=your_jwt_secret_key
      - CORS_ORIGIN=http://localhost:3000
      - NODE_ENV=development
    volumes:
      - ./back_end:/app
      - /app/node_modules
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
